function [e07, None1] = dataImport_iliya(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [E07, NONE1] = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [E07, NONE1] = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  [e07, None1] = importfile("C:\Users\n01388138\Downloads\3_MODULES_1100_Ep.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 27-May-2021 12:20:20

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "e07", "None1", "Var4"];
opts.SelectedVariableNames = ["e07", "None1"];
opts.VariableTypes = ["string", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var4"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var4"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
e07 = tbl.e07;
None1 = tbl.None1;
end